import jsPDF from 'jspdf';
import { PredictionResult } from './types';

export function downloadCSV(results: PredictionResult[]) {
  const headers = ['ID', 'Date', 'Image', 'Severity', 'Overall Risk %', 'Diabetic Retinopathy', 'DR Confidence', 'Glaucoma', 'GL Confidence', 'AMD', 'AMD Confidence', 'Cataracts', 'CT Confidence'];
  const rows = results.map((r) => {
    const dr = r.predictions.find((p) => p.disease === 'Diabetic Retinopathy');
    const gl = r.predictions.find((p) => p.disease === 'Glaucoma');
    const amd = r.predictions.find((p) => p.disease === 'Age-related Macular Degeneration');
    const ct = r.predictions.find((p) => p.disease === 'Cataracts');
    return [
      r.id, r.timestamp, r.imageName, r.severity, r.overallRisk,
      dr?.detected ? 'Yes' : 'No', ((dr?.confidence ?? 0) * 100).toFixed(1),
      gl?.detected ? 'Yes' : 'No', ((gl?.confidence ?? 0) * 100).toFixed(1),
      amd?.detected ? 'Yes' : 'No', ((amd?.confidence ?? 0) * 100).toFixed(1),
      ct?.detected ? 'Yes' : 'No', ((ct?.confidence ?? 0) * 100).toFixed(1),
    ].join(',');
  });

  const csv = [headers.join(','), ...rows].join('\n');
  downloadFile(csv, 'retina_analysis_results.csv', 'text/csv');
}

export function downloadPDFReport(result: PredictionResult) {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.setTextColor(23, 120, 132);
  doc.text('RetinaAI - Analysis Report', 20, 25);
  
  doc.setDrawColor(23, 120, 132);
  doc.setLineWidth(0.5);
  doc.line(20, 30, 190, 30);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Report ID: ${result.id}`, 20, 40);
  doc.text(`Date: ${new Date(result.timestamp).toLocaleString()}`, 20, 46);
  doc.text(`Image: ${result.imageName}`, 20, 52);

  doc.setFontSize(14);
  doc.setTextColor(30);
  doc.text('Diagnosis Summary', 20, 66);

  doc.setFontSize(12);
  const severityColor: Record<string, [number, number, number]> = {
    Normal: [34, 139, 34], Mild: [218, 165, 32], Moderate: [255, 140, 0],
    Severe: [220, 53, 69], Proliferative: [139, 0, 0],
  };
  const color = severityColor[result.severity] || [0, 0, 0];
  doc.setTextColor(...color);
  doc.text(`Severity: ${result.severity}`, 20, 76);
  doc.text(`Overall Risk: ${result.overallRisk}%`, 20, 84);

  doc.setFontSize(14);
  doc.setTextColor(30);
  doc.text('Disease Predictions', 20, 100);

  let y = 110;
  result.predictions.forEach((p) => {
    doc.setFontSize(11);
    doc.setTextColor(50);
    doc.text(p.disease, 20, y);
    doc.setTextColor(p.detected ? 220 : 34, p.detected ? 53 : 139, p.detected ? 69 : 34);
    doc.text(p.detected ? 'DETECTED' : 'Not Detected', 120, y);
    doc.setTextColor(100);
    doc.text(`Confidence: ${(p.confidence * 100).toFixed(1)}%`, 160, y);
    y += 10;
  });

  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text('This report is generated by RetinaAI CNN-based analysis system.', 20, 270);
  doc.text('For clinical decisions, always consult a qualified ophthalmologist.', 20, 276);

  doc.save(`retina_report_${result.id.slice(0, 8)}.pdf`);
}

export function downloadNotebook() {
  const notebook = {
    cells: [
      { cell_type: 'markdown', source: ['# CNN Model for Retina Disease Detection\n', '## Architecture Overview\n', 'This notebook contains the CNN model architecture for automated detection of:\n', '- Diabetic Retinopathy\n', '- Glaucoma\n', '- Age-related Macular Degeneration\n', '- Cataracts'] },
      { cell_type: 'code', source: [
        'import tensorflow as tf\n',
        'from tensorflow.keras import layers, models\n\n',
        'def build_retina_cnn(input_shape=(224, 224, 3), num_classes=4):\n',
        '    model = models.Sequential([\n',
        '        # Block 1: Feature Extraction\n',
        '        layers.Conv2D(32, (3, 3), activation="relu", padding="same", input_shape=input_shape),\n',
        '        layers.BatchNormalization(),\n',
        '        layers.Conv2D(32, (3, 3), activation="relu", padding="same"),\n',
        '        layers.MaxPooling2D((2, 2)),\n',
        '        layers.Dropout(0.25),\n\n',
        '        # Block 2: Deeper Features\n',
        '        layers.Conv2D(64, (3, 3), activation="relu", padding="same"),\n',
        '        layers.BatchNormalization(),\n',
        '        layers.Conv2D(64, (3, 3), activation="relu", padding="same"),\n',
        '        layers.MaxPooling2D((2, 2)),\n',
        '        layers.Dropout(0.25),\n\n',
        '        # Block 3: High-level Features\n',
        '        layers.Conv2D(128, (3, 3), activation="relu", padding="same"),\n',
        '        layers.BatchNormalization(),\n',
        '        layers.Conv2D(128, (3, 3), activation="relu", padding="same"),\n',
        '        layers.MaxPooling2D((2, 2)),\n',
        '        layers.Dropout(0.25),\n\n',
        '        # Block 4: Abstract Features\n',
        '        layers.Conv2D(256, (3, 3), activation="relu", padding="same"),\n',
        '        layers.BatchNormalization(),\n',
        '        layers.Conv2D(256, (3, 3), activation="relu", padding="same"),\n',
        '        layers.GlobalAveragePooling2D(),\n\n',
        '        # Classification Head\n',
        '        layers.Dense(512, activation="relu"),\n',
        '        layers.BatchNormalization(),\n',
        '        layers.Dropout(0.5),\n',
        '        layers.Dense(256, activation="relu"),\n',
        '        layers.Dropout(0.3),\n',
        '        layers.Dense(num_classes, activation="sigmoid")  # Multi-label\n',
        '    ])\n',
        '    return model\n\n',
        'model = build_retina_cnn()\n',
        'model.summary()'
      ], execution_count: null, outputs: [] },
      { cell_type: 'code', source: [
        '# Compile the model\n',
        'model.compile(\n',
        '    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),\n',
        '    loss="binary_crossentropy",\n',
        '    metrics=["accuracy", tf.keras.metrics.AUC(name="auc")]\n',
        ')\n\n',
        '# Training configuration\n',
        'BATCH_SIZE = 32\n',
        'EPOCHS = 50\n',
        'IMG_SIZE = (224, 224)\n\n',
        '# Data augmentation\n',
        'data_augmentation = tf.keras.Sequential([\n',
        '    layers.RandomFlip("horizontal_and_vertical"),\n',
        '    layers.RandomRotation(0.2),\n',
        '    layers.RandomZoom(0.1),\n',
        '    layers.RandomContrast(0.1),\n',
        '])'
      ], execution_count: null, outputs: [] },
    ],
    metadata: { kernelspec: { display_name: 'Python 3', language: 'python', name: 'python3' }, language_info: { name: 'python', version: '3.9.0' } },
    nbformat: 4, nbformat_minor: 5,
  };

  downloadFile(JSON.stringify(notebook, null, 2), 'retina_cnn_model.ipynb', 'application/json');
}

export function downloadDocumentation() {
  const doc = new jsPDF();
  
  doc.setFontSize(22);
  doc.setTextColor(23, 120, 132);
  doc.text('RetinaAI - Dataset & Methodology', 20, 25);
  doc.line(20, 30, 190, 30);

  const sections = [
    { title: 'Dataset Information', y: 45, content: [
      'Training Data: 80,000+ fundus images from public datasets',
      'Sources: EyePACS, ODIR, REFUGE, iChallenge-AMD',
      'Resolution: 224x224 pixels (resized from original)',
      'Classes: Diabetic Retinopathy, Glaucoma, AMD, Cataracts',
      'Split: 70% training, 15% validation, 15% test',
    ]},
    { title: 'Model Architecture', y: 110, content: [
      'Type: Convolutional Neural Network (CNN)',
      'Layers: 4 convolutional blocks + classification head',
      'Parameters: ~3.2M trainable parameters',
      'Input: 224x224x3 RGB fundus images',
      'Output: 4-class multi-label sigmoid activation',
    ]},
    { title: 'Performance Metrics', y: 175, content: [
      'Overall Accuracy: 94.2%',
      'AUC-ROC: 0.967',
      'Sensitivity: 92.8%',
      'Specificity: 95.1%',
      'F1-Score: 0.935',
    ]},
  ];

  sections.forEach((s) => {
    doc.setFontSize(14);
    doc.setTextColor(30);
    doc.text(s.title, 20, s.y);
    doc.setFontSize(10);
    doc.setTextColor(60);
    s.content.forEach((line, i) => {
      doc.text(`• ${line}`, 25, s.y + 12 + i * 8);
    });
  });

  doc.save('retina_ai_documentation.pdf');
}

function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
